#!/bin/bash

echo ""
echo "Applying migration PensionAutoEnrolment"

echo "Adding routes to conf/app.routes"

echo "" >> ../conf/app.routes
echo "GET        /pensionAutoEnrolment                        controllers.PensionAutoEnrolmentController.onPageLoad(mode: Mode = NormalMode)" >> ../conf/app.routes
echo "POST       /pensionAutoEnrolment                        controllers.PensionAutoEnrolmentController.onSubmit(mode: Mode = NormalMode)" >> ../conf/app.routes

echo "GET        /changePensionAutoEnrolment                  controllers.PensionAutoEnrolmentController.onPageLoad(mode: Mode = CheckMode)" >> ../conf/app.routes
echo "POST       /changePensionAutoEnrolment                  controllers.PensionAutoEnrolmentController.onSubmit(mode: Mode = CheckMode)" >> ../conf/app.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "pensionAutoEnrolment.title = pensionAutoEnrolment" >> ../conf/messages.en
echo "pensionAutoEnrolment.heading = pensionAutoEnrolment" >> ../conf/messages.en
echo "pensionAutoEnrolment.checkYourAnswersLabel = pensionAutoEnrolment" >> ../conf/messages.en
echo "pensionAutoEnrolment.error.required = Select yes if pensionAutoEnrolment" >> ../conf/messages.en

echo "Adding to UserAnswersEntryGenerators"
awk '/trait UserAnswersEntryGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryPensionAutoEnrolmentUserAnswersEntry: Arbitrary[(PensionAutoEnrolmentPage.type, JsValue)] =";\
    print "    Arbitrary {";\
    print "      for {";\
    print "        page  <- arbitrary[PensionAutoEnrolmentPage.type]";\
    print "        value <- arbitrary[Boolean].map(Json.toJson(_))";\
    print "      } yield (page, value)";\
    print "    }";\
    next }1' ../test/generators/UserAnswersEntryGenerators.scala > tmp && mv tmp ../test/generators/UserAnswersEntryGenerators.scala

echo "Adding to PageGenerators"
awk '/trait PageGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryPensionAutoEnrolmentPage: Arbitrary[PensionAutoEnrolmentPage.type] =";\
    print "    Arbitrary(PensionAutoEnrolmentPage)";\
    next }1' ../test/generators/PageGenerators.scala > tmp && mv tmp ../test/generators/PageGenerators.scala

echo "Adding to UserAnswersGenerator"
awk '/val generators/ {\
    print;\
    print "    arbitrary[(PensionAutoEnrolmentPage.type, JsValue)] ::";\
    next }1' ../test/generators/UserAnswersGenerator.scala > tmp && mv tmp ../test/generators/UserAnswersGenerator.scala

echo "Migration PensionAutoEnrolment completed"
